#!/usr/bin/env bash


################## load oh-my-zsh tpl ####################
source ~/.zshrc.from.ohmyzsh


################## load confeverig cnf ###################
for config in ~/.confeverig/*
do
    if [[ -f $config ]]; then
        source $config
    fi
done
unset config


################## export my env ########################
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/env/lib
export LIBRARY_PATH=$LIBRARY_PATH:$HOME/env/lib
export PATH=$PATH:~/env/bin
export C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/env/include
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/env/include


################## load all alias ########################
for script in $HOME/scripts/*;do
    if [[ -f $script ]];then
        source $script
        echo "source $script"
    fi
done
unset script

#################### git related  ########################
git config --global user.name "lunzhoufei"
git config --global user.email "lunzhoufei@gmail.com"
git config --global core.editor "vim"
git config --global merge.conflictstyle diff3
git config --global merge.tool vimdiff
git config --global mergetool.prompt true


#################### golang related  #####################
export GO111MODULE=on
export GOROOT=$HOME/goroot/go
export GOPATH=$HOME/gopath
export GOBIN=$HOME/gopath/bin
export PATH=$PATH:$GOPATH/bin:$GOBIN:$GOROOT/bin
export GOSUMDB="off"
export GOPROXY=https://goproxy.io,direct
# export GOPROXY=https://goproxy.cn


####################      Others     #####################
export LC_ALL=zh_CN.utf8 


cat << EOF

██╗     ██╗   ██╗███╗   ██╗███████╗██╗  ██╗ ██████╗ ██╗   ██╗███████╗███████╗██╗
██║     ██║   ██║████╗  ██║╚══███╔╝██║  ██║██╔═══██╗██║   ██║██╔════╝██╔════╝██║
██║     ██║   ██║██╔██╗ ██║  ███╔╝ ███████║██║   ██║██║   ██║█████╗  █████╗  ██║
██║     ██║   ██║██║╚██╗██║ ███╔╝  ██╔══██║██║   ██║██║   ██║██╔══╝  ██╔══╝  ██║
███████╗╚██████╔╝██║ ╚████║███████╗██║  ██║╚██████╔╝╚██████╔╝██║     ███████╗██║
╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝     ╚══════╝╚═╝
                                                                                
                                                                                
                                                                                
EOF
                                                                                
